version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - '8888:8080'
    volumes:
      - ./frontend:/app
    command: npm run serve
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    command: npm start
  nginx:
    image: "nginx:latest"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    build: ./nginx
    ports:
      - '80:80'
  db:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoapp
    ports:
      - '13306:3306'
